[package]
name = "microknot-server"
version = "0.2.0"
edition = "2024"
description = "Local-first workflow engine"
license = "AGPL-3.0"
repository = "https://github.com/BersisSe/microknot"
publish = false
readme = 
[[bin]]
name = "microknot"
path = "src/main.rs"

[dependencies]
microknot-core = { path = "../microknot-core", version="0.2.0"}
clap = { version = "4", features = ["derive", "env"] }
feather = { version = "0.8", features = ["json"] }
rust-embed = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
ureq = "3"